# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: zip the build
      run: |
        echo "web: java -jar ${{ github.event.repository.name }}-${{ github.event.inputs.version }}.jar" > Procfile
        zip -r ../${{ github.event.repository.name }}-${{ github.event.inputs.version }}.zip .platform .ebextensions Procfile ./*.jar